#include "/Engine/Private/Common.ush"
#include "/Engine/Private/RayTracing/RayTracingCommon.ush"
#include "/Engine/Private/Visualization.ush"

#include "/Plugin/UnrealAudioGPU/Public/AudioRays.ush"

    
RaytracingAccelerationStructure SceneBVH;
float3 CharacterPos;
uint NumEmitters;

StructuredBuffer<float3> EmitterPosBuffer;
RWStructuredBuffer<float4> OutputBuffer;

RAY_TRACING_ENTRY_RAYGEN(SoundTracingRGS)
{
    if(DispatchRaysIndex().x >= NumEmitters) return;
    
    float3 origin = EmitterPosBuffer[DispatchRaysIndex().x];
    float3 target = CharacterPos;

    const float3 TLASOffset = View.TLASPreViewTranslationHigh + View.TLASPreViewTranslationLow;

    float3 newOrigin = origin + TLASOffset;
    float3 newTarget = target + TLASOffset;

    float3 rayVector = newTarget - newOrigin;

    RayDesc Ray;
    Ray.Origin = newOrigin;
    Ray.Direction = normalize(rayVector);
    Ray.TMin = 0.1f;
    Ray.TMax = length(rayVector);
 
    uint RayFlags = RAY_FLAG_FORCE_OPAQUE;
    

    FMinimalPayload Payload = (FMinimalPayload) 0;	
    TraceRay(
        SceneBVH,   // AccelerationStructure
        RayFlags,
        RAY_TRACING_MASK_OPAQUE_FP_WORLD_SPACE ,
        //RAY_TRACING_MASK_OPAQUE,          // InstanceInclusionMask, defined by UE4
        RAY_TRACING_SHADER_SLOT_MATERIAL, // RayContributionToHitGroupIndex, defined by UE4
        RAY_TRACING_NUM_SHADER_SLOTS,     // MultiplierForGeometryContributionToShaderIndex, defined by UE4
        0,      // MissShaderIndex
        Ray,    // RayDesc
        Payload // Payload
    );
 
    float3 hitPoint = newOrigin + Ray.Direction * Payload.HitT;
    hitPoint -= TLASOffset; // transform back to world space
    if (Payload.IsHit())
    {
        OutputBuffer[DispatchRaysIndex().x] = float4(hitPoint, 1);
    }
    else
    {
        OutputBuffer[DispatchRaysIndex().x] = float4(target, 0);
    }
}


RAY_TRACING_ENTRY_MISS(SoundTracingMS, FDefaultPayload, Payload)
{
    Payload.SetMiss();
}

RAY_TRACING_ENTRY_CLOSEST_HIT(SoundTracingCHS, FMinimalPayload, Payload, FRayTracingIntersectionAttributes, Attributes)
{
    Payload.HitT = RayTCurrent();
}