#pragma once
#include "/Engine/Public/Platform.ush"

uint Resolution;
RWTexture2D<float2> OutTex;

[numthreads(8, 8, 1)]
void ReturnUV(uint3 DispatchThreadID : SV_DispatchThreadID)
{
    if(DispatchThreadID.x >= Resolution || DispatchThreadID.y >= Resolution) return;
    
    const float TexelSize = 1.0/ float(Resolution);

    float2 UV = (float2(DispatchThreadID.xy) + 0.5) * TexelSize;
    OutTex[DispatchThreadID.xy] = UV;
    //OutTex[DispatchThreadID.xy] = 1.0.xx;
}
